
# /software/slac/workspace/lsst/lacquer/python/lacquer/parsers/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '2351237EEA94EDF95A95B3E1A41B9DC9'
    
_lr_action_items = {'INTEGER':([7,],[9,]),'IDENTIFIER':([0,1,],[1,3,]),'RPAREN':([9,],[10,]),'LPAREN':([3,5,],[-5,7,]),'$end':([2,3,4,5,6,8,10,],[0,-5,-1,-6,-2,-4,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'type':([1,],[4,]),'base_type':([1,],[5,]),'table_element':([0,],[2,]),'type_parameter_opt':([5,],[6,]),'empty':([5,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> table_element","S'",1,None,None,None),
  ('table_element -> IDENTIFIER type','table_element',2,'p_table_element','parser.py',295),
  ('type -> base_type type_parameter_opt','type',2,'p_type','parser.py',300),
  ('type_parameter_opt -> LPAREN INTEGER RPAREN','type_parameter_opt',3,'p_type_parameter_opt','parser.py',305),
  ('type_parameter_opt -> empty','type_parameter_opt',1,'p_type_parameter_opt','parser.py',306),
  ('base_type -> IDENTIFIER','base_type',1,'p_base_type','parser.py',311),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',419),
]
